pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.{ts,tsx,js,json,jsonc}"
      run: bunx oxfmt {staged_files}
      stage_fixed: true
    lint:
      glob: "*.{ts,tsx,js}"
      run: bunx oxlint {staged_files}

pre-push:
  commands:
    typecheck:
      run: bun run typecheck
    test:
      run: bun run test
    lint:
      run: bun run lint
